# Generated by Django 6.0.7 on 2026-07-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_task_parent_task_alter_subtask_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
